//
//  backend.swift
//  YelpRBC
//
//  Created by Reid Ellis on 2016-10-10.
//  Copyright © 2016 Tnir Technologies. All rights reserved.
//

import Foundation
import Alamofire
import SwiftyJSON

class Backend {

	fileprivate	static let apiKey = "v1KQWvOJli4Y69nvfBr4DQ"
	fileprivate	static let secret = "acNRn4t246u2CWRR3EzG4US38ApoyaRcWb7ouVFXwFwNaYZI4uLz59G4Atz0uMdU"
	fileprivate static let apiTokenUrlString = "https://api.yelp.com/oauth2/token"
	fileprivate	static let apiUrlString = "https://api.yelp.com/v3/"
	fileprivate static let searchPrefix = "businesses/search/"

	var tokenString : String? = nil
	var urlString = "https://api.yelp.com/v3/businesses/search"

	open func search(for term: String) {
		// the token string returned by the Yelp OAuth server for our client id and secret

		// get the OAuth token, valid for 3 months
		let req = request("https://api.yelp.com/oauth2/token",
		                  method: .post,
		                  parameters: ["client_id":		Backend.apiKey,
		                               "client_secret":	Backend.secret,
		                               "grant_type":	"client_credentials"],
		                  encoding: URLEncoding.httpBody)
		

		// try to parse the response as JSON data
		req .responseString(completionHandler: { (response) in
				print(response)
			})

			.responseJSON { (response) in
				print(response.request)  // original URL request
				print(response.response) // HTTP URL response
				print(response.data)     // server data
				print(response.result)   // result of response serialization

				if let JSON = response.result.value {
					print("JSON: \(JSON)")
					if let dict = JSON as? Dictionary<String, AnyObject> {
						self.tokenString = dict["access_token"] as? String
						print("access_token 1 = \(self.tokenString)")
						self.searchYelp(for:term)
					}
				}
			}
	}

	open func searchYelp(for term: String) {
		print("access_token 2 = \(self.tokenString)")
		let s : String
		if self.tokenString != nil {
			s = self.tokenString!
		} else {
			s = ""
		}
		print("s is \(s)")

		// if we didn't get a token, Yelp may be unavailable
		guard let token = self.tokenString else {
			return;
		}

		// OAuth headers
		let headers: HTTPHeaders = [
			"Authorization": "Bearer \(token)"
		]

		// ask for Thai food
		request(urlString,
		        method: .get,
		        parameters: ["term": term,
		                     "latitude": "43.7444648",
		                     "longitude": "-79.2026048"],
		        headers: headers
			).responseJSON { (response) in
				print(response.request)  // original URL request
				print(response.response) // HTTP URL response
				print(response.data)     // server data
				print(response.result)   // result of response serialization

				let json = JSON(response.result.value)
				for business in json["businesses"].arrayValue {
					print(business["name"])
				}
//				if let jsonDict = response.result.value {
//					print("JSON: \(jsonDict)")
//					if let dict = jsonDict as? Dictionary<String, AnyObject> {
//						print("[1] = \(dict["businesses"]?[0])")
//					}
//				}
		}
	}
	// this list is from https://www.yelp.com/developers/documentation/v2/category_list
	// it's a shame there isn't an API that returns it
	static let categories = [
		"active": "Active Life",
		"atvrentals": "ATV Rentals/Tours",
		"airsoft": "Airsoft",
		"amateursportsteams": "Amateur Sports Teams",
		"amusementparks": "Amusement Parks",
		"aquariums": "Aquariums",
		"archery": "Archery",
		"badminton": "Badminton",
		"baseballfields": "Baseball Fields",
		"basketballcourts": "Basketball Courts",
		"battingcages": "Batting Cages",
		"beachequipmentrental": "Beach Equipment Rentals",
		"beaches": "Beaches",
		"bikeparking": "Bike Parking",
		"bikerentals": "Bike Rentals",
		"boating": "Boating",
		"bocceball": "Bocce Ball",
		"bowling": "Bowling",
		"bungeejumping": "Bungee Jumping",
		"carousels": "Carousels",
		"challengecourses": "Challenge Courses",
		"climbing": "Climbing",
		"cyclingclasses": "Cycling Classes",
		"daycamps": "Day Camps",
		"discgolf": "Disc Golf",
		"diving": "Diving",
		"freediving": "Free Diving",
		"scuba": "Scuba Diving",
		"escapegames": "Escape Games",
		"fencing": "Fencing Clubs",
		"fishing": "Fishing",
		"fitness": "Fitness & Instruction",
		"barreclasses": "Barre Classes",
		"bootcamps": "Boot Camps",
		"boxing": "Boxing",
		"cardioclasses": "Cardio Classes",
		"dancestudio": "Dance Studios",
		"golflessons": "Golf Lessons",
		"gyms": "Gyms",
		"martialarts": "Martial Arts",
		"meditationcenters": "Meditation Centers",
		"pilates": "Pilates",
		"qigong": "Qi Gong",
		"swimminglessons": "Swimming Lessons/Schools",
		"taichi": "Tai Chi",
		"healthtrainers": "Trainers",
		"yoga": "Yoga",
		"flyboarding": "Flyboarding",
		"gokarts": "Go Karts",
		"golf": "Golf",
		"gun_ranges": "Gun/Rifle Ranges",
		"gymnastics": "Gymnastics",
		"hanggliding": "Hang Gliding",
		"hiking": "Hiking",
		"horseracing": "Horse Racing",
		"horsebackriding": "Horseback Riding",
		"hot_air_balloons": "Hot Air Balloons",
		"jetskis": "Jet Skis",
		"kids_activities": "Kids Activities",
		"kiteboarding": "Kiteboarding",
		"lakes": "Lakes",
		"lasertag": "Laser Tag",
		"leisure_centers": "Leisure Centers",
		"mini_golf": "Mini Golf",
		"mountainbiking": "Mountain Biking",
		"nudist": "Nudist",
		"paddleboarding": "Paddleboarding",
		"paintball": "Paintball",
		"parasailing": "Parasailing",
		"parks": "Parks",
		"dog_parks": "Dog Parks",
		"skate_parks": "Skate Parks",
		"playgrounds": "Playgrounds",
		"races": "Races & Competitions",
		"racingexperience": "Racing Experience",
		"rafting": "Rafting/Kayaking",
		"recreation": "Recreation Centers",
		"rock_climbing": "Rock Climbing",
		"sailing": "Sailing",
		"scavengerhunts": "Scavenger Hunts",
		"seniorcenters": "Senior Centers",
		"skatingrinks": "Skating Rinks",
		"skydiving": "Skydiving",
		"sledding": "Sledding",
		"snorkeling": "Snorkeling",
		"football": "Soccer",
		"sports_clubs": "Sports Clubs",
		"squash": "Squash",
		"summer_camps": "Summer Camps",
		"surfing": "Surfing",
		"swimmingpools": "Swimming Pools",
		"tennis": "Tennis",
		"trampoline": "Trampoline Parks",
		"tubing": "Tubing",
		"waterparks": "Water Parks",
		"wildlifehunting": "Wildlife Hunting Ranges",
		"zipline": "Ziplining",
		"zoos": "Zoos",
		"zorbing": "Zorbing",
		"arts": "Arts & Entertainment",
		"arcades": "Arcades",
		"galleries": "Art Galleries",
		"bingo": "Bingo Halls",
		"gardens": "Botanical Gardens",
		"cabaret": "Cabaret",
		"casinos": "Casinos",
		"movietheaters": "Cinema",
		"driveintheater": "Drive-In Theater",
		"outdoormovies": "Outdoor Movies",
		"countryclubs": "Country Clubs",
		"culturalcenter": "Cultural Center",
		"farms": "Farms",
		"attractionfarms": "Attraction Farms",
		"pickyourown": "Pick Your Own Farms",
		"ranches": "Ranches",
		"festivals": "Festivals",
		"hauntedhouses": "Haunted Houses",
		"jazzandblues": "Jazz & Blues",
		"lancenters": "LAN Centers",
		"museums": "Museums",
		"artmuseums": "Art Museums",
		"childrensmuseums": "Children's Museums",
		"musicvenues": "Music Venues",
		"observatories": "Observatories",
		"opera": "Opera & Ballet",
		"paintandsip": "Paint & Sip",
		"theater": "Performing Arts",
		"planetarium": "Planetarium",
		"sportsteams": "Professional Sports Teams",
		"psychic_astrology": "Psychics & Astrologers",
		"racetracks": "Race Tracks",
		"rodeo": "Rodeo",
		"social_clubs": "Social Clubs",
		"veteransorganizations": "Veterans Organizations",
		"stadiumsarenas": "Stadiums & Arenas",
		"studiotaping": "Studio Taping",
		"ticketsales": "Ticket Sales",
		"wineries": "Wineries",
		"winetastingroom": "Wine Tasting Room",
		"auto": "Automotive",
		"aircraftdealers": "Aircraft Dealers",
		"aircraftrepairs": "Aircraft Repairs",
		"autocustomization": "Auto Customization",
		"auto_detailing": "Auto Detailing",
		"autoglass": "Auto Glass Services",
		"autoloanproviders": "Auto Loan Providers",
		"autopartssupplies": "Auto Parts & Supplies",
		"autorepair": "Auto Repair",
		"diyautoshop": "DIY Auto Shop",
		"autosecurity": "Auto Security",
		"autoupholstery": "Auto Upholstery",
		"boatdealers": "Boat Dealers",
		"bodyshops": "Body Shops",
		"carauctions": "Car Auctions",
		"carbrokers": "Car Brokers",
		"carbuyers": "Car Buyers",
		"car_dealers": "Car Dealers",
		"autodamageassessment": "Car Inspectors",
		"carshares": "Car Share Services",
		"stereo_installation": "Car Stereo Installation",
		"carwash": "Car Wash",
		"truckdealers": "Commercial Truck Dealers",
		"truckrepair": "Commercial Truck Repair",
		"evchargingstations": "EV Charging Stations",
		"fueldocks": "Fuel Docks",
		"servicestations": "Gas & Service Stations",
		"marinas": "Marinas",
		"mobiledentrepair": "Mobile Dent Repair",
		"mobilityequipment": "Mobility Equipment Sales & Services",
		"motorcycledealers": "Motorcycle Dealers",
		"motorcyclerepair": "Motorcycle Repair",
		"motodealers": "Motorsport Vehicle Dealers",
		"motorepairs": "Motorsport Vehicle Repairs",
		"oilchange": "Oil Change Stations",
		"parking": "Parking",
		"rv_dealers": "RV Dealers",
		"rvrepair": "RV Repair",
		"registrationservices": "Registration Services",
		"roadsideassist": "Roadside Assistance",
		"smog_check_stations": "Smog Check Stations",
		"tires": "Tires",
		"towing": "Towing",
		"trailerdealers": "Trailer Dealers",
		"trailerrepair": "Trailer Repair",
		"transmissionrepair": "Transmission Repair",
		"truck_rental": "Truck Rental",
		"usedcardealers": "Used Car Dealers",
		"vehicleshipping": "Vehicle Shipping",
		"vehiclewraps": "Vehicle Wraps",
		"wheelrimrepair": "Wheel & Rim Repair",
		"windshieldinstallrepair": "Windshield Installation & Repair",
		"beautysvc": "Beauty & Spas",
		"acnetreatment": "Acne Treatment",
		"barbers": "Barbers",
		"cosmetics": "Cosmetics & Beauty Supply",
		"spas": "Day Spas",
		"eyelashservice": "Eyelash Service",
		"hair_extensions": "Hair Extensions",
		"hairloss": "Hair Loss Centers",
		"hairremoval": "Hair Removal",
		"laser_hair_removal": "Laser Hair Removal",
		"sugaring": "Sugaring",
		"threadingservices": "Threading Services",
		"waxing": "Waxing",
		"hair": "Hair Salons",
		"blowoutservices": "Blow Dry/Out Services",
		"hair_extensions": "Hair Extensions",
		"hairstylists": "Hair Stylists",
		"menshair": "Men's Hair Salons",
		"hotsprings": "Hot Springs",
		"makeupartists": "Makeup Artists",
		"massage": "Massage",
		"medicalspa": "Medical Spas",
		"othersalons": "Nail Salons",
		"nailtechnicians": "Nail Technicians",
		"perfume": "Perfume",
		"permanentmakeup": "Permanent Makeup",
		"piercing": "Piercing",
		"rolfing": "Rolfing",
		"skincare": "Skin Care",
		"tanning": "Tanning",
		"spraytanning": "Spray Tanning",
		"tanningbeds": "Tanning Beds",
		"tattoo": "Tattoo",
		"teethwhitening": "Teeth Whitening",
		"education": "Education",
		"adultedu": "Adult Education",
		"artclasses": "Art Classes",
		"collegecounseling": "College Counseling",
		"collegeuniv": "Colleges & Universities",
		"educationservices": "Educational Services",
		"elementaryschools": "Elementary Schools",
		"highschools": "Middle Schools & High Schools",
		"montessori": "Montessori Schools",
		"preschools": "Preschools",
		"privateschools": "Private Schools",
		"privatetutors": "Private Tutors",
		"religiousschools": "Religious Schools",
		"specialed": "Special Education",
		"specialtyschools": "Specialty Schools",
		"artschools": "Art Schools",
		"bartendingschools": "Bartending Schools",
		"cprclasses": "CPR Classes",
		"childbirthedu": "Childbirth Education",
		"cookingschools": "Cooking Schools",
		"cosmetology_schools": "Cosmetology Schools",
		"duischools": "DUI Schools",
		"dance_schools": "Dance Schools",
		"driving_schools": "Driving Schools",
		"firearmtraining": "Firearm Training",
		"firstaidclasses": "First Aid Classes",
		"flightinstruction": "Flight Instruction",
		"foodsafety": "Food Safety Training",
		"language_schools": "Language Schools",
		"massage_schools": "Massage Schools",
		"nursingschools": "Nursing Schools",
		"parentingclasses": "Parenting Classes",
		"poledancingclasses": "Pole Dancing Classes",
		"skischools": "Ski Schools",
		"swimminglessons": "Swimming Lessons/Schools",
		"trafficschools": "Traffic Schools",
		"vocation": "Vocational & Technical School",
		"tastingclasses": "Tasting Classes",
		"cheesetastingclasses": "Cheese Tasting Classes",
		"winetasteclasses": "Wine Tasting Classes",
		"testprep": "Test Preparation",
		"tutoring": "Tutoring Centers",
		"eventservices": "Event Planning & Services",
		"bartenders": "Bartenders",
		"boatcharters": "Boat Charters",
		"stationery": "Cards & Stationery",
		"caricatures": "Caricatures",
		"catering": "Caterers",
		"clowns": "Clowns",
		"djs": "DJs",
		"facepainting": "Face Painting",
		"gametruckrental": "Game Truck Rental",
		"golfcartrentals": "Golf Cart Rentals",
		"hennaartists": "Henna Artists",
		"hotels": "Hotels",
		"mountainhuts": "Mountain Huts",
		"reststops": "Rest Stops",
		"magicians": "Magicians",
		"mohels": "Mohels",
		"musicians": "Musicians",
		"officiants": "Officiants",
		"eventplanning": "Party & Event Planning",
		"partybikerentals": "Party Bike Rentals",
		"partybusrentals": "Party Bus Rentals",
		"partycharacters": "Party Characters",
		"partyequipmentrentals": "Party Equipment Rentals",
		"partysupplies": "Party Supplies",
		"personalchefs": "Personal Chefs",
		"photoboothrentals": "Photo Booth Rentals",
		"photographers": "Photographers",
		"eventphotography": "Event Photography",
		"sessionphotography": "Session Photography",
		"silentdisco": "Silent Disco",
		"sommelierservices": "Sommelier Services",
		"teambuilding": "Team Building Activities",
		"triviahosts": "Trivia Hosts",
		"valetservices": "Valet Services",
		"venues": "Venues & Event Spaces",
		"videographers": "Videographers",
		"weddingchappels": "Wedding Chapels",
		"wedding_planning": "Wedding Planning",
		"financialservices": "Financial Services",
		"banks": "Banks & Credit Unions",
		"businessfinancing": "Business Financing",
		"paydayloans": "Check Cashing/Pay-day Loans",
		"currencyexchange": "Currency Exchange",
		"debtrelief": "Debt Relief Services",
		"financialadvising": "Financial Advising",
		"installmentloans": "Installment Loans",
		"insurance": "Insurance",
		"autoinsurance": "Auto Insurance",
		"homeinsurance": "Home & Rental Insurance",
		"lifeinsurance": "Life Insurance",
		"investing": "Investing",
		"taxservices": "Tax Services",
		"titleloans": "Title Loans",
		"food": "Food",
		"acaibowls": "Acai Bowls",
		"bagels": "Bagels",
		"bakeries": "Bakeries",
		"beer_and_wine": "Beer, Wine & Spirits",
		"breweries": "Breweries",
		"bubbletea": "Bubble Tea",
		"butcher": "Butcher",
		"csa": "CSA",
		"chimneycakes": "Chimney Cakes",
		"cideries": "Cideries",
		"coffee": "Coffee & Tea",
		"coffeeroasteries": "Coffee Roasteries",
		"convenience": "Convenience Stores",
		"cupcakes": "Cupcakes",
		"customcakes": "Custom Cakes",
		"desserts": "Desserts",
		"distilleries": "Distilleries",
		"diyfood": "Do-It-Yourself Food",
		"donuts": "Donuts",
		"empanadas": "Empanadas",
		"farmersmarket": "Farmers Market",
		"fooddeliveryservices": "Food Delivery Services",
		"foodtrucks": "Food Trucks",
		"gelato": "Gelato",
		"grocery": "Grocery",
		"honey": "Honey",
		"icecream": "Ice Cream & Frozen Yogurt",
		"importedfood": "Imported Food",
		"intlgrocery": "International Grocery",
		"internetcafe": "Internet Cafes",
		"juicebars": "Juice Bars & Smoothies",
		"kombucha": "Kombucha",
		"organic_stores": "Organic Stores",
		"cakeshop": "Patisserie/Cake Shop",
		"poke": "Poke",
		"pretzels": "Pretzels",
		"shavedice": "Shaved Ice",
		"shavedsnow": "Shaved Snow",
		"gourmet": "Specialty Food",
		"candy": "Candy Stores",
		"cheese": "Cheese Shops",
		"chocolate": "Chocolatiers & Shops",
		"markets": "Fruits & Veggies",
		"healthmarkets": "Health Markets",
		"herbsandspices": "Herbs & Spices",
		"macarons": "Macarons",
		"meats": "Meat Shops",
		"oliveoil": "Olive Oil",
		"pastashops": "Pasta Shops",
		"popcorn": "Popcorn Shops",
		"seafoodmarkets": "Seafood Markets",
		"streetvendors": "Street Vendors",
		"tea": "Tea Rooms",
		"waterstores": "Water Stores",
		"wineries": "Wineries",
		"winetastingroom": "Wine Tasting Room",
		"health": "Health & Medical",
		"acupuncture": "Acupuncture",
		"assistedliving": "Assisted Living Facilities",
		"ayurveda": "Ayurveda",
		"behavioranalysts": "Behavior Analysts",
		"blooddonation": "Blood & Plasma Donation Centers",
		"cannabis_clinics": "Cannabis Clinics",
		"cannabistours": "Cannabis Tours",
		"chiropractors": "Chiropractors",
		"colonics": "Colonics",
		"conciergemedicine": "Concierge Medicine",
		"c_and_mh": "Counseling & Mental Health",
		"psychologists": "Psychologists",
		"sextherapists": "Sex Therapists",
		"sportspsychologists": "Sports Psychologists",
		"cryotherapy": "Cryotherapy",
		"dentalhygienists": "Dental Hygienists",
		"dentists": "Dentists",
		"cosmeticdentists": "Cosmetic Dentists",
		"endodontists": "Endodontists",
		"generaldentistry": "General Dentistry",
		"oralsurgeons": "Oral Surgeons",
		"orthodontists": "Orthodontists",
		"pediatric_dentists": "Pediatric Dentists",
		"periodontists": "Periodontists",
		"diagnosticservices": "Diagnostic Services",
		"diagnosticimaging": "Diagnostic Imaging",
		"laboratorytesting": "Laboratory Testing",
		"dialysisclinics": "Dialysis Clinics",
		"dietitians": "Dietitians",
		"physicians": "Doctors",
		"addictionmedicine": "Addiction Medicine",
		"allergist": "Allergists",
		"anesthesiologists": "Anesthesiologists",
		"audiologist": "Audiologist",
		"cardiology": "Cardiologists",
		"cosmeticsurgeons": "Cosmetic Surgeons",
		"dermatology": "Dermatologists",
		"earnosethroat": "Ear Nose & Throat",
		"emergencymedicine": "Emergency Medicine",
		"endocrinologists": "Endocrinologists",
		"familydr": "Family Practice",
		"fertility": "Fertility",
		"gastroenterologist": "Gastroenterologist",
		"geneticists": "Geneticists",
		"gerontologist": "Gerontologists",
		"hepatologists": "Hepatologists",
		"hospitalists": "Hospitalists",
		"immunodermatologists": "Immunodermatologists",
		"infectiousdisease": "Infectious Disease Specialists",
		"internalmed": "Internal Medicine",
		"naturopathic": "Naturopathic/Holistic",
		"nephrologists": "Nephrologists",
		"neurologist": "Neurologist",
		"neuropathologists": "Neuropathologists",
		"neurotologists": "Neurotologists",
		"obgyn": "Obstetricians & Gynecologists",
		"oncologist": "Oncologist",
		"opthamalogists": "Ophthalmologists",
		"orthopedists": "Orthopedists",
		"osteopathicphysicians": "Osteopathic Physicians",
		"otologists": "Otologists",
		"painmanagement": "Pain Management",
		"pathologists": "Pathologists",
		"pediatricians": "Pediatricians",
		"phlebologists": "Phlebologists",
		"podiatrists": "Podiatrists",
		"preventivemedicine": "Preventive Medicine",
		"proctologist": "Proctologists",
		"psychiatrists": "Psychiatrists",
		"pulmonologist": "Pulmonologist",
		"radiologists": "Radiologists",
		"rhematologists": "Rheumatologists",
		"spinesurgeons": "Spine Surgeons",
		"sportsmed": "Sports Medicine",
		"surgeons": "Surgeons",
		"tattooremoval": "Tattoo Removal",
		"toxicologists": "Toxicologists",
		"underseamedicine": "Undersea/Hyperbaric Medicine",
		"urologists": "Urologists",
		"vascularmedicine": "Vascular Medicine",
		"doulas": "Doulas",
		"emergencyrooms": "Emergency Rooms",
		"floatspa": "Float Spa",
		"habilitativeservices": "Habilitative Services",
		"halfwayhouses": "Halfway Houses",
		"halotherapy": "Halotherapy",
		"healthinsurance": "Health Insurance Offices",
		"hearingaidproviders": "Hearing Aid Providers",
		"herbalshops": "Herbal Shops",
		"homehealthcare": "Home Health Care",
		"hospice": "Hospice",
		"hospitals": "Hospitals",
		"hydrotherapy": "Hydrotherapy",
		"hypnosis": "Hypnosis/Hypnotherapy",
		"ivhydration": "IV Hydration",
		"lactationservices": "Lactation Services",
		"laserlasikeyes": "Laser Eye Surgery/Lasik",
		"liceservices": "Lice Services",
		"massage_therapy": "Massage Therapy",
		"cannabisreferrals": "Medical Cannabis Referrals",
		"medcenters": "Medical Centers",
		"walkinclinics": "Walk-in Clinics",
		"medicalspa": "Medical Spas",
		"medicaltransportation": "Medical Transportation",
		"midwives": "Midwives",
		"nursepractitioner": "Nurse Practitioner",
		"nutritionists": "Nutritionists",
		"occupationaltherapy": "Occupational Therapy",
		"optometrists": "Optometrists",
		"organdonorservices": "Organ & Tissue Donor Services",
		"orthotics": "Orthotics",
		"oxygenbars": "Oxygen Bars",
		"personalcare": "Personal Care Services",
		"physicaltherapy": "Physical Therapy",
		"placentaencapsulation": "Placenta Encapsulations",
		"prenatal": "Prenatal/Perinatal Care",
		"prosthetics": "Prosthetics",
		"prosthodontists": "Prosthodontists",
		"reflexology": "Reflexology",
		"rehabilitation_center": "Rehabilitation Center",
		"reiki": "Reiki",
		"retirement_homes": "Retirement Homes",
		"saunas": "Saunas",
		"skillednursing": "Skilled Nursing",
		"sleepspecialists": "Sleep Specialists",
		"speech_therapists": "Speech Therapists",
		"spermclinic": "Sperm Clinic",
		"tcm": "Traditional Chinese Medicine",
		"tuina": "Tui Na",
		"urgent_care": "Urgent Care",
		"weightlosscenters": "Weight Loss Centers",
		"homeservices": "Home Services",
		"artificialturf": "Artificial Turf",
		"buildingsupplies": "Building Supplies",
		"cabinetry": "Cabinetry",
		"carpenters": "Carpenters",
		"carpetinstallation": "Carpet Installation",
		"carpeting": "Carpeting",
		"childproofing": "Childproofing",
		"chimneysweeps": "Chimney Sweeps",
		"contractors": "Contractors",
		"countertopinstall": "Countertop Installation",
		"damagerestoration": "Damage Restoration",
		"decksrailing": "Decks & Railing",
		"demolitionservices": "Demolition Services",
		"doorsales": "Door Sales/Installation",
		"drywall": "Drywall Installation & Repair",
		"electricians": "Electricians",
		"fencesgates": "Fences & Gates",
		"fireprotection": "Fire Protection Services",
		"fireplace": "Fireplace Services",
		"firewood": "Firewood",
		"flooring": "Flooring",
		"furnitureassembly": "Furniture Assembly",
		"garage_door_services": "Garage Door Services",
		"gardeners": "Gardeners",
		"glassandmirrors": "Glass & Mirrors",
		"gutterservices": "Gutter Services",
		"handyman": "Handyman",
		"hvac": "Heating & Air Conditioning/HVAC",
		"seasonaldecorservices": "Holiday Decorating Services",
		"homeautomation": "Home Automation",
		"homecleaning": "Home Cleaning",
		"homeenergyauditors": "Home Energy Auditors",
		"home_inspectors": "Home Inspectors",
		"homenetworkinstall": "Home Network Installation",
		"home_organization": "Home Organization",
		"hometheatreinstallation": "Home Theatre Installation",
		"homewindowtinting": "Home Window Tinting",
		"housesitters": "House Sitters",
		"insulationinstallation": "Insulation Installation",
		"interiordesign": "Interior Design",
		"isps": "Internet Service Providers",
		"irrigation": "Irrigation",
		"locksmiths": "Keys & Locksmiths",
		"landscapearchitects": "Landscape Architects",
		"landscaping": "Landscaping",
		"lighting": "Lighting Fixtures & Equipment",
		"masonry_concrete": "Masonry/Concrete",
		"movers": "Movers",
		"packingservices": "Packing Services",
		"painters": "Painters",
		"patiocoverings": "Patio Coverings",
		"plumbing": "Plumbing",
		"backflowservices": "Backflow Services",
		"poolservice": "Pool & Hot Tub Service",
		"poolcleaners": "Pool Cleaners",
		"pressurewashers": "Pressure Washers",
		"realestate": "Real Estate",
		"apartments": "Apartments",
		"artspacerentals": "Art Space Rentals",
		"commercialrealestate": "Commercial Real Estate",
		"condominiums": "Condominiums",
		"estateliquidation": "Estate Liquidation",
		"homedevelopers": "Home Developers",
		"homestaging": "Home Staging",
		"homeownerassociation": "Homeowner Association",
		"housingcooperatives": "Housing Cooperatives",
		"kitchenincubators": "Kitchen Incubators",
		"mobilehomes": "Mobile Home Dealers",
		"mobileparks": "Mobile Home Parks",
		"mortgagebrokers": "Mortgage Brokers",
		"propertymgmt": "Property Management",
		"realestateagents": "Real Estate Agents",
		"realestatesvcs": "Real Estate Services",
		"landsurveying": "Land Surveying",
		"estatephotography": "Real Estate Photography",
		"sharedofficespaces": "Shared Office Spaces",
		"university_housing": "University Housing",
		"refinishing": "Refinishing Services",
		"roofinspectors": "Roof Inspectors",
		"roofing": "Roofing",
		"securitysystems": "Security Systems",
		"blinds": "Shades & Blinds",
		"shutters": "Shutters",
		"solarinstallation": "Solar Installation",
		"solarpanelcleaning": "Solar Panel Cleaning",
		"structuralengineers": "Structural Engineers",
		"stucco": "Stucco Services",
		"televisionserviceproviders": "Television Service Providers",
		"tiling": "Tiling",
		"treeservices": "Tree Services",
		"utilities": "Utilities",
		"vinylsiding": "Vinyl Siding",
		"waterheaterinstallrepair": "Water Heater Installation/Repair",
		"waterpurification": "Water Purification Services",
		"waterproofing": "Waterproofing",
		"windowwashing": "Window Washing",
		"windowsinstallation": "Windows Installation",
		"hotelstravel": "Hotels & Travel",
		"airports": "Airports",
		"airportterminals": "Airport Terminals",
		"bedbreakfast": "Bed & Breakfast",
		"campgrounds": "Campgrounds",
		"carrental": "Car Rental",
		"guesthouses": "Guest Houses",
		"healthretreats": "Health Retreats",
		"hostels": "Hostels",
		"hotels": "Hotels",
		"mountainhuts": "Mountain Huts",
		"reststops": "Rest Stops",
		"motorcycle_rental": "Motorcycle Rental",
		"rvparks": "RV Parks",
		"rvrental": "RV Rental",
		"resorts": "Resorts",
		"skiresorts": "Ski Resorts",
		"tours": "Tours",
		"aerialtours": "Aerial Tours",
		"architecturaltours": "Architectural Tours",
		"arttours": "Art Tours",
		"boattours": "Boat Tours",
		"bustours": "Bus Tours",
		"foodtours": "Food Tours",
		"historicaltours": "Historical Tours",
		"scootertours": "Scooter Tours",
		"walkingtours": "Walking Tours",
		"whalewatchingtours": "Whale Watching Tours",
		"winetours": "Wine Tours",
		"trainstations": "Train Stations",
		"transport": "Transportation",
		"airlines": "Airlines",
		"airport_shuttles": "Airport Shuttles",
		"bikesharing": "Bike Sharing",
		"busstations": "Bus Stations",
		"buses": "Buses",
		"cablecars": "Cable Cars",
		"limos": "Limos",
		"metrostations": "Metro Stations",
		"pedicabs": "Pedicabs",
		"privatejetcharter": "Private Jet Charter",
		"publictransport": "Public Transportation",
		"taxis": "Taxis",
		"towncarservice": "Town Car Service",
		"trains": "Trains",
		"travelservices": "Travel Services",
		"luggagestorage": "Luggage Storage",
		"passportvisaservices": "Passport & Visa Services",
		"travelagents": "Travel Agents",
		"visitorcenters": "Visitor Centers",
		"vacationrentalagents": "Vacation Rental Agents",
		"vacation_rentals": "Vacation Rentals",
		"localflavor": "Local Flavor",
		"publicart": "Public Art",
		"unofficialyelpevents": "Unofficial Yelp Events",
		"yelpevents": "Yelp Events",
		"localservices": "Local Services",
		"3dprinting": "3D Printing",
		"adoptionservices": "Adoption Services",
		"airductcleaning": "Air Duct Cleaning",
		"homeappliancerepair": "Appliances & Repair",
		"appraisalservices": "Appraisal Services",
		"artrestoration": "Art Restoration",
		"awnings": "Awnings",
		"bailbondsmen": "Bail Bondsmen",
		"bike_repair_maintenance": "Bike Repair/Maintenance",
		"bookbinding": "Bookbinding",
		"calligraphy": "Calligraphy",
		"carpet_cleaning": "Carpet Cleaning",
		"childcare": "Child Care & Day Care",
		"clockrepair": "Clock Repair",
		"communitybookbox": "Community Book Box",
		"communitygardens": "Community Gardens",
		"nonprofit": "Community Service/Non-Profit",
		"foodbanks": "Food Banks",
		"homelessshelters": "Homeless Shelters",
		"couriers": "Couriers & Delivery Services",
		"craneservices": "Crane Services",
		"drycleaninglaundry": "Dry Cleaning & Laundry",
		"eldercareplanning": "Elder Care Planning",
		"electronicsrepair": "Electronics Repair",
		"engraving": "Engraving",
		"enviroabatement": "Environmental Abatement",
		"environmentaltesting": "Environmental Testing",
		"farmequipmentrepair": "Farm Equipment Repair",
		"fingerprinting": "Fingerprinting",
		"funeralservices": "Funeral Services & Cemeteries",
		"rentfurniture": "Furniture Rental",
		"furniturerepair": "Furniture Repair",
		"reupholstery": "Furniture Reupholstery",
		"hydrojetting": "Hydro-jetting",
		"itservices": "IT Services & Computer Repair",
		"datarecovery": "Data Recovery",
		"mobilephonerepair": "Mobile Phone Repair",
		"telecommunications": "Telecommunications",
		"jewelryrepair": "Jewelry Repair",
		"junkremovalandhauling": "Junk Removal & Hauling",
		"dumpsterrental": "Dumpster Rental",
		"junkyards": "Junkyards",
		"knifesharpening": "Knife Sharpening",
		"machinerental": "Machine & Tool Rental",
		"machineshops": "Machine Shops",
		"mailboxcenters": "Mailbox Centers",
		"metalfabricators": "Metal Fabricators",
		"musicinstrumentservices": "Musical Instrument Services",
		"guitarstores": "Guitar Stores",
		"pianoservices": "Piano Services",
		"pianostores": "Piano Stores",
		"nannys": "Nanny Services",
		"notaries": "Notaries",
		"pest_control": "Pest Control",
		"powdercoating": "Powder Coating",
		"copyshops": "Printing Services",
		"propane": "Propane",
		"recording_studios": "Recording & Rehearsal Studios",
		"recyclingcenter": "Recycling Center",
		"sandblasting": "Sandblasting",
		"screenprinting": "Screen Printing",
		"screen_printing_tshirt_printing": "Screen Printing/T-Shirt Printing",
		"selfstorage": "Self Storage",
		"septicservices": "Septic Services",
		"sewingalterations": "Sewing & Alterations",
		"shipping_centers": "Shipping Centers",
		"shoerepair": "Shoe Repair",
		"shoeshine": "Shoe Shine",
		"snowremoval": "Snow Removal",
		"tvmounting": "TV Mounting",
		"watch_repair": "Watch Repair",
		"waterdelivery": "Water Delivery",
		"welldrilling": "Well Drilling",
		"wildlifecontrol": "Wildlife Control",
		"massmedia": "Mass Media",
		"printmedia": "Print Media",
		"radiostations": "Radio Stations",
		"televisionstations": "Television Stations",
		"nightlife": "Nightlife",
		"adultentertainment": "Adult Entertainment",
		"barcrawl": "Bar Crawl",
		"bars": "Bars",
		"airportlounges": "Airport Lounges",
		"beerbar": "Beer Bar",
		"champagne_bars": "Champagne Bars",
		"cocktailbars": "Cocktail Bars",
		"divebars": "Dive Bars",
		"drivethrubars": "Drive-Thru Bars",
		"gaybars": "Gay Bars",
		"hookah_bars": "Hookah Bars",
		"irish_pubs": "Irish Pub",
		"lounges": "Lounges",
		"pubs": "Pubs",
		"speakeasies": "Speakeasies",
		"sportsbars": "Sports Bars",
		"tikibars": "Tiki Bars",
		"vermouthbars": "Vermouth Bars",
		"whiskeybars": "Whiskey Bars",
		"wine_bars": "Wine Bars",
		"beergardens": "Beer Gardens",
		"clubcrawl": "Club Crawl",
		"comedyclubs": "Comedy Clubs",
		"countrydancehalls": "Country Dance Halls",
		"danceclubs": "Dance Clubs",
		"jazzandblues": "Jazz & Blues",
		"karaoke": "Karaoke",
		"musicvenues": "Music Venues",
		"pianobars": "Piano Bars",
		"poolhalls": "Pool Halls",
		"pets": "Pets",
		"animalshelters": "Animal Shelters",
		"horse_boarding": "Horse Boarding",
		"petadoption": "Pet Adoption",
		"petservices": "Pet Services",
		"animalphysicaltherapy": "Animal Physical Therapy",
		"aquariumservices": "Aquarium Services",
		"dogwalkers": "Dog Walkers",
		"emergencypethospital": "Emergency Pet Hospital",
		"farriers": "Farriers",
		"animalholistic": "Holistic Animal Care",
		"pet_sitting": "Pet Boarding/Pet Sitting",
		"petbreeders": "Pet Breeders",
		"petcremation": "Pet Cremation Services",
		"groomer": "Pet Groomers",
		"pethospice": "Pet Hospice",
		"petinsurance": "Pet Insurance",
		"petphotography": "Pet Photography",
		"pet_training": "Pet Training",
		"pettransport": "Pet Transportation",
		"petstore": "Pet Stores",
		"birdshops": "Bird Shops",
		"localfishstores": "Local Fish Stores",
		"reptileshops": "Reptile Shops",
		"vet": "Veterinarians",
		"professional": "Professional Services",
		"accountants": "Accountants",
		"advertising": "Advertising",
		"architects": "Architects",
		"billingservices": "Billing Services",
		"boatrepair": "Boat Repair",
		"bookkeepers": "Bookkeepers",
		"businessconsulting": "Business Consulting",
		"careercounseling": "Career Counseling",
		"commissionedartists": "Commissioned Artists",
		"customsbrokers": "Customs Brokers",
		"digitizingservices": "Digitizing Services",
		"duplicationservices": "Duplication Services",
		"editorialservices": "Editorial Services",
		"employmentagencies": "Employment Agencies",
		"fengshui": "Feng Shui",
		"graphicdesign": "Graphic Design",
		"indoorlandscaping": "Indoor Landscaping",
		"isps": "Internet Service Providers",
		"lawyers": "Lawyers",
		"bankruptcy": "Bankruptcy Law",
		"businesslawyers": "Business Law",
		"contractlaw": "Contract Law",
		"criminaldefense": "Criminal Defense Law",
		"duilawyers": "DUI Law",
		"divorce": "Divorce & Family Law",
		"employmentlawyers": "Employment Law",
		"entertainmentlaw": "Entertainment Law",
		"estateplanning": "Estate Planning Law",
		"willstrustsprobates": "Wills, Trusts, & Probates",
		"general_litigation": "General Litigation",
		"iplaw": "IP & Internet Law",
		"immigrationlawyers": "Immigration Law",
		"medicallaw": "Medical Law",
		"personal_injury": "Personal Injury Law",
		"realestatelawyers": "Real Estate Law",
		"taxlaw": "Tax Law",
		"trafficticketinglaw": "Traffic Ticketing Law",
		"workerscomplaw": "Workers Compensation Law",
		"legalservices": "Legal Services",
		"processservers": "Process Servers",
		"lifecoach": "Life Coach",
		"marketing": "Marketing",
		"matchmakers": "Matchmakers",
		"mediators": "Mediators",
		"musicproduction": "Music Production Services",
		"officecleaning": "Office Cleaning",
		"patentlaw": "Patent Law",
		"payroll": "Payroll Services",
		"personalassistants": "Personal Assistants",
		"privateinvestigation": "Private Investigation",
		"productdesign": "Product Design",
		"publicrelations": "Public Relations",
		"security": "Security Services",
		"shredding": "Shredding Services",
		"signmaking": "Signmaking",
		"softwaredevelopment": "Software Development",
		"talentagencies": "Talent Agencies",
		"taxidermy": "Taxidermy",
		"tenantlaw": "Tenant and Eviction Law",
		"translationservices": "Translation Services",
		"videofilmproductions": "Video/Film Production",
		"web_design": "Web Design",
		"wholesalers": "Wholesalers",
		"publicservicesgovt": "Public Services & Government",
		"communitycenters": "Community Centers",
		"courthouses": "Courthouses",
		"departmentsofmotorvehicles": "Departments of Motor Vehicles",
		"embassy": "Embassy",
		"firedepartments": "Fire Departments",
		"landmarks": "Landmarks & Historical Buildings",
		"libraries": "Libraries",
		"policedepartments": "Police Departments",
		"postoffices": "Post Offices",
		"realestate": "Real Estate",
		"apartments": "Apartments",
		"artspacerentals": "Art Space Rentals",
		"commercialrealestate": "Commercial Real Estate",
		"condominiums": "Condominiums",
		"estateliquidation": "Estate Liquidation",
		"homedevelopers": "Home Developers",
		"homestaging": "Home Staging",
		"homeownerassociation": "Homeowner Association",
		"housingcooperatives": "Housing Cooperatives",
		"kitchenincubators": "Kitchen Incubators",
		"mobilehomes": "Mobile Home Dealers",
		"mobileparks": "Mobile Home Parks",
		"mortgagebrokers": "Mortgage Brokers",
		"propertymgmt": "Property Management",
		"realestateagents": "Real Estate Agents",
		"realestatesvcs": "Real Estate Services",
		"landsurveying": "Land Surveying",
		"estatephotography": "Real Estate Photography",
		"sharedofficespaces": "Shared Office Spaces",
		"university_housing": "University Housing",
		"religiousorgs": "Religious Organizations",
		"buddhist_temples": "Buddhist Temples",
		"churches": "Churches",
		"hindu_temples": "Hindu Temples",
		"mosques": "Mosques",
		"synagogues": "Synagogues",
		"restaurants": "Restaurants",
		"afghani": "Afghan",
		"african": "African",
		"senegalese": "Senegalese",
		"southafrican": "South African",
		"newamerican": "American (New)",
		"tradamerican": "American (Traditional)",
		"arabian": "Arabian",
		"argentine": "Argentine",
		"armenian": "Armenian",
		"asianfusion": "Asian Fusion",
		"australian": "Australian",
		"austrian": "Austrian",
		"bangladeshi": "Bangladeshi",
		"bbq": "Barbeque",
		"basque": "Basque",
		"belgian": "Belgian",
		"brasseries": "Brasseries",
		"brazilian": "Brazilian",
		"breakfast_brunch": "Breakfast & Brunch",
		"british": "British",
		"buffets": "Buffets",
		"burgers": "Burgers",
		"burmese": "Burmese",
		"cafes": "Cafes",
		"themedcafes": "Themed Cafes",
		"cafeteria": "Cafeteria",
		"cajun": "Cajun/Creole",
		"cambodian": "Cambodian",
		"caribbean": "Caribbean",
		"dominican": "Dominican",
		"haitian": "Haitian",
		"puertorican": "Puerto Rican",
		"trinidadian": "Trinidadian",
		"catalan": "Catalan",
		"cheesesteaks": "Cheesesteaks",
		"chickenshop": "Chicken Shop",
		"chicken_wings": "Chicken Wings",
		"chinese": "Chinese",
		"cantonese": "Cantonese",
		"dimsum": "Dim Sum",
		"hainan": "Hainan",
		"shanghainese": "Shanghainese",
		"szechuan": "Szechuan",
		"comfortfood": "Comfort Food",
		"creperies": "Creperies",
		"cuban": "Cuban",
		"czech": "Czech",
		"delis": "Delis",
		"diners": "Diners",
		"dinnertheater": "Dinner Theater",
		"ethiopian": "Ethiopian",
		"hotdogs": "Fast Food",
		"filipino": "Filipino",
		"fishnchips": "Fish & Chips",
		"fondue": "Fondue",
		"food_court": "Food Court",
		"foodstands": "Food Stands",
		"french": "French",
		"mauritius": "Mauritius",
		"reunion": "Reunion",
		"gastropubs": "Gastropubs",
		"german": "German",
		"gluten_free": "Gluten-Free",
		"greek": "Greek",
		"halal": "Halal",
		"hawaiian": "Hawaiian",
		"himalayan": "Himalayan/Nepalese",
		"hkcafe": "Hong Kong Style Cafe",
		"hotdog": "Hot Dogs",
		"hotpot": "Hot Pot",
		"hungarian": "Hungarian",
		"iberian": "Iberian",
		"indpak": "Indian",
		"indonesian": "Indonesian",
		"irish": "Irish",
		"italian": "Italian",
		"calabrian": "Calabrian",
		"sardinian": "Sardinian",
		"tuscan": "Tuscan",
		"japanese": "Japanese",
		"izakaya": "Izakaya",
		"ramen": "Ramen",
		"teppanyaki": "Teppanyaki",
		"korean": "Korean",
		"kosher": "Kosher",
		"laotian": "Laotian",
		"latin": "Latin American",
		"colombian": "Colombian",
		"salvadoran": "Salvadoran",
		"venezuelan": "Venezuelan",
		"raw_food": "Live/Raw Food",
		"malaysian": "Malaysian",
		"mediterranean": "Mediterranean",
		"falafel": "Falafel",
		"mexican": "Mexican",
		"tacos": "Tacos",
		"mideastern": "Middle Eastern",
		"egyptian": "Egyptian",
		"lebanese": "Lebanese",
		"modern_european": "Modern European",
		"mongolian": "Mongolian",
		"moroccan": "Moroccan",
		"newmexican": "New Mexican Cuisine",
		"nicaraguan": "Nicaraguan",
		"noodles": "Noodles",
		"pakistani": "Pakistani",
		"panasian": "Pan Asian",
		"persian": "Persian/Iranian",
		"peruvian": "Peruvian",
		"pizza": "Pizza",
		"polish": "Polish",
		"popuprestaurants": "Pop-Up Restaurants",
		"portuguese": "Portuguese",
		"poutineries": "Poutineries",
		"russian": "Russian",
		"salad": "Salad",
		"sandwiches": "Sandwiches",
		"scandinavian": "Scandinavian",
		"scottish": "Scottish",
		"seafood": "Seafood",
		"singaporean": "Singaporean",
		"slovakian": "Slovakian",
		"soulfood": "Soul Food",
		"soup": "Soup",
		"southern": "Southern",
		"spanish": "Spanish",
		"srilankan": "Sri Lankan",
		"steak": "Steakhouses",
		"supperclubs": "Supper Clubs",
		"sushi": "Sushi Bars",
		"syrian": "Syrian",
		"taiwanese": "Taiwanese",
		"tapas": "Tapas Bars",
		"tapasmallplates": "Tapas/Small Plates",
		"tex-mex": "Tex-Mex",
		"thai": "Thai",
		"turkish": "Turkish",
		"ukrainian": "Ukrainian",
		"uzbek": "Uzbek",
		"vegan": "Vegan",
		"vegetarian": "Vegetarian",
		"vietnamese": "Vietnamese",
		"waffles": "Waffles",
		"wraps": "Wraps",
		"shopping": "Shopping",
		"adult": "Adult",
		"antiques": "Antiques",
		"galleries": "Art Galleries",
		"artsandcrafts": "Arts & Crafts",
		"artsupplies": "Art Supplies",
		"stationery": "Cards & Stationery",
		"cookingclasses": "Cooking Classes",
		"costumes": "Costumes",
		"embroideryandcrochet": "Embroidery & Crochet",
		"fabricstores": "Fabric Stores",
		"framing": "Framing",
		"paintyourownpottery": "Paint-Your-Own Pottery",
		"auctionhouses": "Auction Houses",
		"baby_gear": "Baby Gear & Furniture",
		"batterystores": "Battery Stores",
		"bespoke": "Bespoke Clothing",
		"media": "Books, Mags, Music & Video",
		"bookstores": "Bookstores",
		"comicbooks": "Comic Books",
		"musicvideo": "Music & DVDs",
		"mags": "Newspapers & Magazines",
		"videogamestores": "Video Game Stores",
		"videoandgames": "Videos & Video Game Rental",
		"vinyl_records": "Vinyl Records",
		"brewingsupplies": "Brewing Supplies",
		"bridal": "Bridal",
		"cannabisdispensaries": "Cannabis Dispensaries",
		"computers": "Computers",
		"cosmetics": "Cosmetics & Beauty Supply",
		"custommerchandise": "Customized Merchandise",
		"deptstores": "Department Stores",
		"discountstore": "Discount Store",
		"drugstores": "Drugstores",
		"dutyfreeshops": "Duty-Free Shops",
		"electronics": "Electronics",
		"opticians": "Eyewear & Opticians",
		"farmingequipment": "Farming Equipment",
		"fashion": "Fashion",
		"accessories": "Accessories",
		"childcloth": "Children's Clothing",
		"clothingrental": "Clothing Rental",
		"deptstores": "Department Stores",
		"formalwear": "Formal Wear",
		"furclothing": "Fur Clothing",
		"hats": "Hats",
		"leather": "Leather Goods",
		"lingerie": "Lingerie",
		"maternity": "Maternity Wear",
		"menscloth": "Men's Clothing",
		"plus_size_fashion": "Plus Size Fashion",
		"shoes": "Shoe Stores",
		"sportswear": "Sports Wear",
		"dancewear": "Dance Wear",
		"surfshop": "Surf Shop",
		"swimwear": "Swimwear",
		"vintage": "Used, Vintage & Consignment",
		"womenscloth": "Women's Clothing",
		"fireworks": "Fireworks",
		"fitnessequipment": "Fitness/Exercise Equipment",
		"fleamarkets": "Flea Markets",
		"flowers": "Flowers & Gifts",
		"stationery": "Cards & Stationery",
		"florists": "Florists",
		"giftshops": "Gift Shops",
		"goldbuyers": "Gold Buyers",
		"guns_and_ammo": "Guns & Ammo",
		"headshops": "Head Shops",
		"hifi": "High Fidelity Audio Equipment",
		"hobbyshops": "Hobby Shops",
		"homeandgarden": "Home & Garden",
		"appliances": "Appliances",
		"christmastrees": "Christmas Trees",
		"furniture": "Furniture Stores",
		"grillingequipment": "Grilling Equipment",
		"hardware": "Hardware Stores",
		"holidaydecorations": "Holiday Decorations",
		"homedecor": "Home Decor",
		"hottubandpool": "Hot Tub & Pool",
		"kitchenandbath": "Kitchen & Bath",
		"mattresses": "Mattresses",
		"gardening": "Nurseries & Gardening",
		"outdoorfurniture": "Outdoor Furniture Stores",
		"paintstores": "Paint Stores",
		"playsets": "Playsets",
		"pumpkinpatches": "Pumpkin Patches",
		"rugs": "Rugs",
		"tableware": "Tableware",
		"horsequipment": "Horse Equipment Shops",
		"jewelry": "Jewelry",
		"knittingsupplies": "Knitting Supplies",
		"livestocksupply": "Livestock Feed & Supply",
		"luggage": "Luggage",
		"medicalsupplies": "Medical Supplies",
		"cellphoneaccessories": "Mobile Phone Accessories",
		"mobilephones": "Mobile Phones",
		"motorcyclinggear": "Motorcycle Gear",
		"musicalinstrumentsandteachers": "Musical Instruments & Teachers",
		"officeequipment": "Office Equipment",
		"outlet_stores": "Outlet Stores",
		"packingsupplies": "Packing Supplies",
		"pawn": "Pawn Shops",
		"perfume": "Perfume",
		"personal_shopping": "Personal Shopping",
		"photographystores": "Photography Stores & Services",
		"poolbilliards": "Pool & Billiards",
		"popupshops": "Pop-up Shops",
		"props": "Props",
		"religiousitems": "Religious Items",
		"shoppingcenters": "Shopping Centers",
		"souvenirs": "Souvenir Shops",
		"spiritual_shop": "Spiritual Shop",
		"sportgoods": "Sporting Goods",
		"bikes": "Bikes",
		"diveshops": "Dive Shops",
		"golfequipment": "Golf Equipment",
		"huntingfishingsupplies": "Hunting & Fishing Supplies",
		"outdoorgear": "Outdoor Gear",
		"skateshops": "Skate Shops",
		"skishops": "Ski & Snowboard Shops",
		"sportswear": "Sports Wear",
		"dancewear": "Dance Wear",
		"tabletopgames": "Tabletop Games",
		"teachersupplies": "Teacher Supplies",
		"thrift_stores": "Thrift Stores",
		"tobaccoshops": "Tobacco Shops",
		"toys": "Toy Stores",
		"trophyshops": "Trophy Shops",
		"uniforms": "Uniforms",
		"usedbooks": "Used Bookstore",
		"vapeshops": "Vape Shops",
		"vitaminssupplements": "Vitamins & Supplements",
		"watches": "Watches",
		"wholesale_stores": "Wholesale Stores",
		"wigs": "Wigs"
	]
}
